# Generated by Django 5.1.7 on 2025-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_choice_image_choice_match_text_question_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_placement_test',
            field=models.BooleanField(default=False),
        ),
    ]
