# Generated by Django 5.2.3 on 2025-06-29 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quizattempt_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question'),
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-start_time']},
        ),
        migrations.RenameField(
            model_name='quizanswer',
            old_name='attempt',
            new_name='quiz_attempt',
        ),
        migrations.RenameField(
            model_name='quizanswer',
            old_name='voice_recording',
            new_name='voice_answer',
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='voicerecording',
            old_name='audio_file',
            new_name='recording',
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='passing_score',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='status',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in the quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=10, help_text='Points for this question', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_points',
            field=models.PositiveIntegerField(default=100, help_text='Maximum points for the quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_answers', to='quizzes.question'),
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='time_taken',
        ),
    ]
