# Generated by Django 5.2.3 on 2025-06-29 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_quizattempt_options_quiz_passing_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_answers', to='quizzes.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='quiz_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'completed'], name='quizzes_qui_student_434600_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'completed'], name='quizzes_qui_quiz_id_b5fe41_idx'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='quiz_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizquestion'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['quiz_attempt'], name='quizzes_qui_quiz_at_927d49_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['attempt'], name='quizzes_qui_attempt_f061cb_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['question'], name='quizzes_qui_questio_4b21cc_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['quiz_question'], name='quizzes_qui_quiz_qu_cbfd9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('attempt__isnull', False), ('question__isnull', False)), fields=('attempt', 'question'), name='unique_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('quiz_attempt__isnull', False), ('question__isnull', False)), fields=('quiz_attempt', 'question'), name='unique_quiz_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('attempt__isnull', False), ('quiz_question__isnull', False)), fields=('attempt', 'quiz_question'), name='unique_attempt_quiz_question'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('quiz_attempt__isnull', False), ('quiz_question__isnull', False)), fields=('quiz_attempt', 'quiz_question'), name='unique_quiz_attempt_quiz_question'),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'question')},
        ),
    ]
