# Generated by Django 5.1.7 on 2025-04-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_assignment_coursematerial_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(default='No instructions provided', help_text='Detailed instructions for completing the assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_text',
            field=models.TextField(blank=True, help_text="Student's text response (if applicable)", null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(help_text='Brief overview of the assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late Submission'), ('resubmit', 'Needs Resubmission')], default='submitted', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_submissions/'),
        ),
    ]
